### ISSUE TITLE
Is this project still available?

### ISSUE THREAD

**Issue by liwanglin12** [dextercai/FEEYO-Adsb#1]
I am very interested in this project. I have set the data sent to FlightAware and FlightRadar24, and now I want to send data to FEEYO.

**Comment by dextercai** [comment]
是的，这个项目依旧是可用的，但由于FEEYO提供的接口有限，暂时不能有更多的内容可供您参考。
你可以再此：http://blog.csdn.net/caiwenzhe 看到使用本项目内容做的搭建。如需更多帮助QQ群：495967823

**Comment by liwanglin12** [comment]
感谢~
