### ISSUE TITLE
咨询关于项目相关

### ISSUE THREAD

**Issue by weeknote** [dextercai/FEEYO-Adsb#3]
请问申请ADS-B接收设备或者自己搭建了之后可以装在自己家吗，您这个项目里的东西是用于共享数据是吗？有没有具体操作的教程，谢谢~~

**Comment by dextercai** [comment]
https://blog.dextercai.com/2018/06/installFeeyoUpdataBash/
您可以查看一下上面这篇博文。
此外，也可以去看一下项目内增补的![官方安装脚本](https://github.com/dextercai/FEEYO-Adsb/tree/master/Official-%E9%A3%9E%E5%B8%B8%E5%87%86ADS-B%E8%84%9A%E6%9C%AC%E7%A8%8B%E5%BA%8F)
里面有一份说明文件，比较详细。
